version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Search2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  georgcav-service:
    build: .
    restart: always
    environment:
      SERVER_PORT: 8086
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Search2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8086:8086"
    depends_on:
      - postgres

volumes:
  pgdata:
