pipeline {
    agent any

    tools {
        maven 'Maven 3.9'
        jdk 'Java 17'
    }

    pipeline {
        // Кардинальное изменение: запускаем всю сборку внутри QA-контейнера, где Chrome уже настроен
        agent {
            docker {
                image 'markhobson/maven-chrome:jdk-17'
                // Даем контейнеру повышенные привилегии и общую память, чтобы Chrome не падал внутри Docker
                args '-v /var/run/docker.sock:/var/run/docker.sock --shm-size=2g'
            }
        }

        stages {
            stage('Запуск автотестов') {
                steps {
                    dir('george') {
                        // Добавили стандартный флаг -Dselenide.headless=true для надежности напрямую в Maven
                        sh "mvn clean test -Dselenide.headless=true -Dspring.profiles.active=test -Dyandex.cloud.s3.access-key=${params.S3_KEY} -Dyandex.cloud.s3.secret-key=${params.S3_SECRET}"
                    }
                }
            }
        }

    post {
        always {

            allure includeProperties: false,
                    jdk: '',
                    properties: [],
                    reportBuildPolicy: 'ALWAYS',
                    results: [[path: 'george/target/surefire-reports']]

            withCredentials([string(credentialsId: 'max_bot_token', variable: 'MAX_TOKEN')]) {
                sh """
                    curl -k -s -X POST "https://platform-api2.max.ru/messages?user_id=13956800" \
                    -H "Authorization: \$MAX_TOKEN" \
                    -H "Content-Type: application/json" \
                    -d '{
                        "text": "🚀 Автотесты Aquilon завершены!\\n\\nСтатус: ${currentBuild.currentResult}\\nСборка: #${env.BUILD_NUMBER}\\n\\n🔗 Отчет Allure: ${env.BUILD_URL}allure/"
                    }'
                """
            }
        }
    }


}
