pipeline {
    agent any

    tools {
        maven 'Maven 3.9'
        jdk 'Java 17'
    }

    stages {
        stage('Запуск автотестов') {
            steps {
                dir('george') {
                    sh "mvn clean test -Dspring.profiles.active=test -Dyandex.cloud.s3.access-key=${params.S3_KEY} -Dyandex.cloud.s3.secret-key=${params.S3_SECRET}"
                }
            }
        }
    }

    post {
        always {
            // Строим отчет Allure по результатам стандартных JUnit XML-логов
            allure includeProperties: false,
                    jdk: '',
                    properties: [],
                    reportBuildPolicy: 'ALWAYS',
                    results: [[path: 'george/target/surefire-reports']]
        }
    }
}
