pipeline {
    agent any

    tools {
        maven 'Maven 3.9'
        jdk 'Java 17'
    }

    stages {
        stage('Сборка и запуск автотестов') {
           dir('george') {
                      sh 'mvn clean test'
                  }
        }
    }

    post {
        always {
            // Генерация и публикация отчета Allure в интерфейсе Jenkins
            allure includeProperties: false,
                   jdk: '',
                   properties: [],
                   reportBuildPolicy: 'ALWAYS',
                   results: [[path: 'target/allure-results']]
        }
    }
}