server.port=8086
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/Search2
spring.datasource.username=postgres
spring.datasource.password=admin
#spring.jpa.show-sql: true
spring.datasource.driver-class-n
ame=org.postgresql.Driver



yandex.cloud.s3.region=ru-central1
yandex.cloud.s3.bucket-name=my-unique-antique-shop-images

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB